### ISSUE TITLE
Update content formatting in Guidelines, FAQs

### ISSUE THREAD

**Issue by fcoveram** [WordPress/wporg-photo-directory#30]
**Describe the solution you'd like**
We could simplify the layout of "Guidelines" page by removing the indentation space in paragraphs placed in "Content" section.

They are unnecessary

![Image](https://github.com/user-attachments/assets/0d1379f0-df9b-4c2a-ae53-095e8204947e)

**Comment by ndiego** [comment]
It looks like the content is using `<dl>` markup. Converting this to simple headings and paragraphs should fix the issue.

**Comment by ryelle** [comment]
[The "FAQ" page](https://wordpress.org/photos/faq/) was also flagged as needing an update, this can also be switched to plain headings & paragraphs, instead of open-by-default details elements.

These updates will happen after/as part of launch, so that we're not changing content on the current site.

**Comment by ndiego** [comment]
> These updates will happen after/as part of launch, so that we're not changing content on the current site.

Perfect!

**Comment by ryelle** [comment]
https://wordpress.org/photos/guidelines/ & https://wordpress.org/photos/faq/ now use plain headings and paragraphs for the content.

**Comment by ndiego** [comment]
> https://wordpress.org/photos/guidelines/ & https://wordpress.org/photos/faq/ now use plain headings and paragraphs for the content.

Nice!
