### ISSUE TITLE
Remove gray background and add a section border in photo details page

### ISSUE THREAD

**Issue by fcoveram** [WordPress/wporg-photo-directory#35]
After revisiting the photo details page and trying a few ideas with @jasmussen, we think that removing the gray background beneath the photo looks better than having it.

The initial idea of adding the background was outlining the container area and align it with the profile image on the left and the download button on the right, but the gray seems to be part of the image. Instead, we like the idea of adding a full-width border in light grey.

Here is a mockup for the above.

![Image](https://github.com/user-attachments/assets/1015ddda-0205-4f91-8b91-eafeee6ca94d)

What do you think of this?

**Comment by ndiego** [comment]
I think removing the grey background is fine, but not sure about the separator. It works on Openverse since the image container is full width, but the container here is set to wide width. 

The one thing I like about Openverse is that the images are set to a max height of `500px` and have no aspect ratio applied. This allows images that are not 16/9 to be full-width on mobile. 🤔

| Portrait | Landscape |
|-|-|
|![Image](https://github.com/user-attachments/assets/4f115c4c-5f7e-4aac-a001-38fcdfbde2df)|![Image](https://github.com/user-attachments/assets/c69218d0-409b-4035-871b-d28e7b0e5da6)|

**Comment by ryelle** [comment]
The outcome from the call was to remove the grey background, and no border.

![Image](https://github.com/user-attachments/assets/36d62550-d1e6-4078-923f-f3a26cb4d40d)

**Comment by fcoveram** [comment]
Perfect. It looks great 🚀
