### ISSUE TITLE
Small vertical image on mobile

### ISSUE THREAD

**Issue by fcoveram** [WordPress/wporg-photo-directory#36]
I noticed that vertical images look very small on mobile, like [this page](https://wordpress.org/photos/photo/19567436fa/).

<img src=https://github.com/user-attachments/assets/118af46b-7b03-4c31-a8eb-b7263e84ee38 width=350>

–

It seems that the aspect ratio of its container causes it. What do you think of removing it on mobile to allow images to reach their biggest size? I checked a few pages and didn't see narrow images that could cause a long scroll.

The outcome of the example linked could look like this.

<img src=https://github.com/user-attachments/assets/f7fca7b1-d65f-496a-bff7-2c6b4e9a649c width=350>

---

What do you think of this?

**Comment by ndiego** [comment]
Yeah, using max-height instead of aspect ratio might solve this to, as noted here: https://github.com/WordPress/wporg-photo-directory/issues/35#issuecomment-2517253218

**Comment by ryelle** [comment]
A max-height of 700 seems good. We can switch at the 600px breakpoint, from the fixed aspect-ratio to that max-height. What do you think?

| 360 | 415 | 560 |
|---|---|---|
| ![Image](https://github.com/user-attachments/assets/6daa642d-5672-4d8a-9292-b3bfcdeeb8d9) | ![Image](https://github.com/user-attachments/assets/160dd3eb-f2ce-4561-a75f-26dfb6ea78a0) | ![Image](https://github.com/user-attachments/assets/48c17724-4e63-4158-988b-eda92af3c951) |

Edit: I picked 700 because a quick glance at popular "mobile" sizes are around 740-900px tall.

**Comment by ndiego** [comment]
Looks good to me

**Comment by fcoveram** [comment]
Looks great 🚀
